void vet1c(int *v);
void vet1d(int *v);
void vet1a(int *v);
void vet2c(int *v);
void vet2d(int *v);
void vet2a(int *v);
void vet3c(int *v);
void vet3d(int *v);
void vet3a(int *v);
void vet4c(int *v);
void vet4d(int *v);
void vet4a(int *v);
void imprimeVetor(int *v);
void bubbleSort(int *v, int tam);
void criaHeap(int *vet, int i, int f);
void heapSort(int *vet, int n);
void insertionSort(int *v, int tam);
void quickSort(int *a, int esq, int dir);
void calculaTempo(int *v, int tam, char tipo);
